name: Trading Bot

on:
  schedule:
    # Run every 5 minutes during market hours (9:30 AM - 4:00 PM EST, Monday-Friday)
    - cron: '*/5 13-20 * * 1-5'  # UTC time (EST + 4 hours)
  workflow_dispatch:  # Allow manual triggering

jobs:
  run-trading-bot:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run trading bot
      env:
        APCA_API_KEY_ID: ${{ secrets.APCA_API_KEY_ID }}
        APCA_API_SECRET_KEY: ${{ secrets.APCA_API_SECRET_KEY }}
        APCA_BASE_URL: https://paper-api.alpaca.markets/v2/account
      run: |
        python src/main.py
    
    - name: Upload logs
      if: always()  # Upload logs even if the bot fails
      uses: actions/upload-artifact@v4
      with:
        name: trading-bot-logs
        path: 
          trading_bot.log
          src/trading_bot.log
        if-no-files-found: warn 
