name: Trading Bot

on:
  schedule:
    # Run at 9:30 AM and 3:55 PM EST on trading days
    - cron: '30 13 * * 1-5'  # 9:30 AM EST
    - cron: '55 19 * * 1-5'  # 3:55 PM EST
  workflow_dispatch:  # Allow manual triggers

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run trading bot
      env:
        APCA_API_KEY_ID: ${{ secrets.APCA_API_KEY_ID }}
        APCA_API_SECRET_KEY: ${{ secrets.APCA_API_SECRET_KEY }}
        APCA_BASE_URL: ${{ secrets.APCA_BASE_URL }}
      run: python bot.py 
